---
- name: restart ntp
  service: name=ntpd state=restarted

- name: restart numad
  service: name=numad state=restarted

- name: restart cgconfig
  service: name=cgconfig state=restarted

- name: restart numad
  service: name=numad state=restarted

- name: restart tuned
  service: name=tuned state=restarted
