---
- name: "Set our default sysctl params" 
  sysctl: name={{ item.key }} value="{{ item.value }}" state=present reload=yes
  ignore_errors: yes
  with_items: 
    - { key: "net.ipv4.ip_forward", value: "0" } 
    - { key: "net.ipv4.conf.default.rp_filter", value: "0" } 
    - { key: "net.ipv4.conf.default.accept_source_route", value: "0" }
    - { key: "kernel.exec-shield", value: "1" }
    - { key: "kernel.randomize_va_space", value: "1" }
    - { key: "kernel.sysrq", value: "0" }
    - { key: "kernel.core_uses_pid", value: "1" }
    - { key: "kernel.panic", value: "30" }
    - { key: "kernel.msgmnb", value: "65536" }
    - { key: "kernel.msgmax", value: "65536" }
    - { key: "kernel.shmmax", value: "68719476736" }
    - { key: "kernel.shmall", value: "4294967296" }
    - { key: "kernel.vsyscall64", value: "1" }
    - { key: "net.ipv4.tcp_rmem", value: "8192 87380 1677721" } 
    - { key: "net.ipv4.tcp_wmem", value: "8192 87380 1677721" } 
    - { key: "net.ipv4.tcp_window_scaling", value: "1" }
    - { key: "net.ipv4.tcp_syncookies", value: "1" }
    - { key: "net.ipv4.tcp_slow_start_after_idle", value: "0" }
    - { key: "net.ipv4.tcp_delack_min", value: "1" }
    - { key: "net.ipv4.tcp_mem", value: "8388608 12582912 16777216" }
    - { key: "net.ipv4.udp_mem", value: "8388608 12582912 16777216" }
    - { key: "net.ipv4.ip_local_port_range", value: "10000 65000" }
    - { key: "net.ipv6.conf.all.disable_ipv6", value: "1" }
    - { key: "net.core.optmem_max", value: "40960" }
    - { key: "net.ipv4.route.secret_interval", value: "864000" }
    - { key: "net.core.netdev_max_backlog", value: "50000" }
    - { key: "net.ipv4.tcp_max_syn_backlog", value: "10000" }
    - { key: "net.ipv4.tcp_tw_reuse", value: "1" }
    - { key: "net.ipv4.tcp_tw_recycle", value: "1" }
    - { key: "net.ipv4.tcp_timestamps", value: "0" }
    - { key: "net.ipv4.tcp_sack", value: "0" }
    - { key: "net.ipv4.tcp_low_latency", value: "1" }
    - { key: "net.core.rmem_default", value: "16777216" }
    - { key: "net.core.rmem_max", value: "16777216" } 
    - { key: "net.core.wmem_max", value: "16777216" }
    - { key: "vm.swappiness", value: "10" }
    - { key: "kernel.hung_task_panic", value: "1" }
    - { key: "kernel.hung_task_timeout_secs", value: "600" }
    - { key: "vm.overcommit_memory", value: "1" }
